# Generated by Django 5.2.1 on 2025-05-22 16:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('possui_ar_condicionado', models.BooleanField()),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_maquinas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_razao_social', models.CharField(max_length=120)),
                ('nome_fantasia', models.CharField(blank=True, max_length=120, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('contato', models.CharField(max_length=50)),
                ('telefone_1', models.CharField(max_length=40)),
                ('telefone_2', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Andamento', 'Andamento'), ('Concluido', 'Concluido')], default='Pendente', max_length=15)),
                ('ambiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.ambiente')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.endereco')),
            ],
        ),
    ]
