# Generated by Django 5.2.1 on 2025-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_ambiente_id_alter_cliente_id_alter_endereco_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
