# Generated by Django 5.2.1 on 2025-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_1',
            field=models.CharField(max_length=40),
        ),
    ]
